name: testing
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pip
  - python
  - xarray
  - xesmf
  - pip:
    - black
    - pytest
    # documentation packages
    - ipython
    - jupyter
    - jupyter-sphinx
    - nbsphinx
    - pandoc
    - pydata-sphinx-theme
    - sphinx
    - sphinx-book-theme
