name: testing
channels:
  - defaults
  - conda-forge
dependencies:
  - black
  - numpy
  - pip
  - python
  - pytest
  - xarray
  - xesmf
  # documentation packages
  - ipython
  - jupyter
  - jupyter-sphinx
  - nbsphinx
  - pandoc
  - pydata-sphinx-theme
  - sphinx
  - sphinx-book-theme
