name: Build Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Conda setup
        uses: conda-incubator/setup-miniconda@v2
        with:
          channels: conda-forge
          python-version: ${{ matrix.python-version }}
          activate-environment: formatting
          auto-activate-base: false

      - name: Set up conda environment
        run: |
          conda env update -f ci/formatting.yml
          python -m pip install --no-deps -e .
      - name: Conda list information
        run: |
          conda env list
          conda list
      - name: Install sphinx and related modules
        run: |
          pip install -r docs/requirements.txt
      - name: Build HTML documentation
        run: |
          cd docs
          make html
